version: '3.8'

# 生产环境Docker Compose配置 - RQ版本
# 使用GitHub Actions构建的镜像 + Redis队列

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: pubmed-redis-prod
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
      - ./logs/redis:/var/log/redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - pubmed-network

  # 主应用服务
  app:
    image: ghcr.io/zhy0504/pubmed-literature-push-web:latest
    container_name: pubmed-literature-push
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      # 覆盖 .env 中的数据库路径，强制使用绝对路径
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
      # Redis配置
      - REDIS_URL=redis://redis:6379/0
      # 时区配置（可通过环境变量覆盖，默认为亚洲/上海）
      - TZ=${TZ:-Asia/Shanghai}
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/app.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pubmed-network

  # RQ Worker进程（生产环境多实例）
  worker-1:
    image: ghcr.io/zhy0504/pubmed-literature-push-web:latest
    container_name: pubmed-rq-worker-1
    command: python /app/rq_worker.py
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
      - REDIS_URL=redis://redis:6379/0
      - RQ_WORKER_NAME=pubmed-worker-prod-1
      - RQ_QUEUES=high,default,low
      - TZ=${TZ:-Asia/Shanghai}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/rq_worker_1.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pubmed-network

  worker-2:
    image: ghcr.io/zhy0504/pubmed-literature-push-web:latest
    container_name: pubmed-rq-worker-2
    command: python /app/rq_worker.py
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
      - REDIS_URL=redis://redis:6379/0
      - RQ_WORKER_NAME=pubmed-worker-prod-2
      - RQ_QUEUES=high,default,low
      - TZ=${TZ:-Asia/Shanghai}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/rq_worker_2.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pubmed-network

  # RQ Scheduler进程（生产环境）
  scheduler:
    image: ghcr.io/zhy0504/pubmed-literature-push-web:latest
    container_name: pubmed-rq-scheduler-prod
    command: python /app/rq_scheduler_runner.py
    env_file:
      - .env
    environment:
      # 数据库配置
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
      # Redis配置
      - REDIS_URL=redis://redis:6379/0
      # Scheduler配置
      - RQ_SCHEDULER_NAME=pubmed-scheduler-prod
      # RQ_SCHEDULER_INTERVAL 已移除，从数据库读取 push_check_frequency
      # 时区配置
      - TZ=${TZ:-Asia/Shanghai}
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/rq_scheduler.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pubmed-network

  # RQ Dashboard（生产环境监控 - 使用 rq-dashboard-fast）
  rq-dashboard:
    image: hannes221/rq-dashboard-fast:latest
    container_name: pubmed-rq-dashboard-prod
    ports:
      - "9181:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - USERNAME=${RQ_DASHBOARD_USER:-admin}
      - PASSWORD=${RQ_DASHBOARD_PASS:-admin123}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - pubmed-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: pubmed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - pubmed-network

volumes:
  redis-data:
    driver: local

networks:
  pubmed-network:
    driver: bridge