version: '3.8'

# RQ版本Docker Compose配置
# 包含Redis队列和Worker进程

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: pubmed-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
      - ./logs/redis:/var/log/redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # 主应用服务
  app:
    build: .
    container_name: pubmed-literature-push
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      # 数据库配置
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
      # Redis配置
      - REDIS_URL=redis://redis:6379/0
      # 时区配置
      - TZ=${TZ:-Asia/Shanghai}
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/app.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RQ Worker进程
  worker:
    build: .
    container_name: pubmed-rq-worker
    command: python rq_worker.py
    env_file:
      - .env
    environment:
      # Redis配置
      - REDIS_URL=redis://redis:6379/0
      # Worker配置
      - RQ_WORKER_NAME=pubmed-worker-docker
      - RQ_QUEUES=high,default,low
      # 时区配置
      - TZ=${TZ:-Asia/Shanghai}
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/rq_worker.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      app:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RQ Scheduler进程
  scheduler:
    build: .
    container_name: pubmed-rq-scheduler
    command: python rq_scheduler.py
    env_file:
      - .env
    environment:
      # Redis配置
      - REDIS_URL=redis://redis:6379/0
      # Scheduler配置
      - RQ_SCHEDULER_NAME=pubmed-scheduler-docker
      - RQ_SCHEDULER_INTERVAL=10
      # 时区配置
      - TZ=${TZ:-Asia/Shanghai}
      # 日志配置
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/rq_scheduler.log
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; redis.Redis.from_url('redis://redis:6379/0').ping()"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RQ Dashboard (可选)
  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    container_name: pubmed-rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
      - RQ_DASHBOARD_USERNAME=${RQ_DASHBOARD_USER:-admin}
      - RQ_DASHBOARD_PASSWORD=${RQ_DASHBOARD_PASS:-admin123}
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - dashboard

  # Nginx反向代理 (生产环境)
  nginx:
    image: nginx:alpine
    container_name: pubmed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    profiles:
      - production

volumes:
  redis-data:
    driver: local

networks:
  default:
    name: pubmed-network