version: '3.8'

# 开发环境的Docker Compose配置
# 使用命令: docker-compose -f docker-compose.dev.yml up

services:
  # 开发环境主应用
  app-dev:
    build:
      context: .
      target: development
    container_name: pubmed-literature-push-dev
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=sqlite:///pubmed_app.db
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    command: ["python", "app.py"]

  # 开发环境Redis
  redis-dev:
    image: redis:7-alpine
    container_name: pubmed-redis-dev
    ports:
      - "6379:6379"
    restart: unless-stopped