version: '3.8'

# 生产环境Docker Compose配置
# 使用GitHub Actions构建的镜像

services:
  # 主应用服务
  app:
    image: ghcr.io/zhy0504/pubmed-literature-push-web:latest
    container_name: pubmed-literature-push
    ports:
      - "5003:5003"
    env_file:
      - .env
    environment:
      # 覆盖 .env 中的数据库路径，强制使用绝对路径
      - DATABASE_URL=sqlite:////app/data/pubmed_app.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: pubmed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped